# Generated by Django 2.1.3 on 2018-11-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('room_type', models.CharField(max_length=50)),
                ('places', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=5)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
    ]
